version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"  # Exposes MongoDB port to the host
    volumes:
      - mongo_data:/data/db  # Persists data on the host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    networks:
      - mongo_network

volumes:
  mongo_data:
    driver: local

networks:
  mongo_network:
    driver: bridge
